/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dembol' at '19.11.15 22:52' with Gradle 2.5
 *
 * @author dembol, @date 19.11.15 22:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
